version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16.3
    working_directory: /go/src/github.com/heckdevice/moxy
    steps:
      - checkout
      - run:
          name: run build
          command: |
            go build -v
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./...
  docker:
      environment:
        IMAGE_NAME: jsrcorp/moxy
      docker:
        - image: circleci/buildpack-deps:stretch
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Moxy docker image
            command: make build
workflows:
  version: 2
  build-docker:
    jobs:
      - build
      - docker:
          requires:
            - build
          filters:
            branches:
              only: main