version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16.3
    working_directory: /go/src/github.com/heckdevice/moxy
    steps:
      - checkout
      - run:
          name: run build
          command: |
            go build -v
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./...
  deploy:
    docker:
      - image: circleci/golang:1.16.3
    working_directory: /go/src/github.com/heckdevice/moxy
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: go get -u github.com/stevenmatthewt/semantics
      - run:
          name: cross compile
          command: |
            make build
            #gox -os="linux darwin windows" -arch="amd64" -output="dist/moxy_{{.OS}}_{{.Arch}}"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main